# Create directories to store final and intermediate results

mkdir -p relancer-exp/patches
mkdir -p relancer-exp/fixed_notebooks
mkdir -p relancer-exp/exec-logs

# Run Relancer on all the Jupyter Notebooks used in the evaluation
(
    cd relancer/scripts/full
    ./relancer.sh
)

# Remove irrelevant files produced by the notebooks
find relancer-exp/fixed_notebooks/ -type f ! -name "*.py" | xargs rm &> /dev/null

# Show the list of patches generated by Relancer
echo '=== Patches: '
find relancer-exp/patches
