#!/bin/bash

cd ../../

date

time timeout 1800 python main.py --mode relancer --project gregorut_videogamesales --notebook did-you-said-basics-eda-ml-for-very-beginners --strategy apidoc # ------
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook ibm-hr-prediction-and-data-visualization --strategy apidoc
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook insightful-eda-churn-customers-models-pipeline --strategy apidoc
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook first-kaggle-stat-analysis-eda-adjusted-r-2-87 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project vjchoudhary7_customer-segmentation-tutorial-in-python --notebook unsupervised-learning-applications --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook student-s-academic-performance-with-ml-eda --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook heart-disease-prediction-with-ml-models --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook machine-learning-classification --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook an-eda-on-sap --strategy apidoc
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook end-to-end-ml-project --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook california-housing-tutorial --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project alopez247_pokemon --notebook sklearn-tutorial --strategy apidoc
time timeout 1800 python main.py --mode relancer --project imnikhilanand_heart-attack-prediction --notebook heart-attack-detection-proj1 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project janiobachmann_bank-marketing-dataset --notebook bank-marketing-campaign-opening-a-term-deposit --strategy apidoc
time timeout 1800 python main.py --mode relancer --project janiobachmann_bank-marketing-dataset --notebook marketing-campaign --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aungpyaeap_fish-market --notebook kernel49cd9d947d --strategy apidoc
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook telecom-churn --strategy apidoc
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook bank-churn-modelling --strategy apidoc
time timeout 1800 python main.py --mode relancer --project fayomi_advertising --notebook ad-click-prediction-using-logistic-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mansoordaku_ckdisease --notebook data-cleaning-classification-algorithms-comparison --strategy apidoc
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook decision-tree-f1-98-acc-99-auc-99 --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook income-prediction-using-multi-model-and-eda --strategy apidoc
time timeout 1800 python main.py --mode relancer --project loveall_appliances-energy-prediction --notebook appliance-energy-prediction --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project ruslankl_mice-protein-expression --notebook behavior-based-on-protein-expression-using-svm --strategy apidoc
time timeout 1800 python main.py --mode relancer --project jruvika_fake-news-detection --notebook fake-news-classifier --strategy apidoc
time timeout 1800 python main.py --mode relancer --project madislemsalu_facebook-ad-campaign --notebook who-is-likely-to-have-approved-transactions --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kingburrito666_shakespeare-plays --notebook text-generation-using-shakespeare-plays --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project kandij_diabetes-dataset --notebook diabetics-prediction-using-logistic-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project gunner38_horseracing --notebook logistic-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rtatman_us-candy-production-by-month --notebook sweet-time-series --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook application-of-supervised-ml-classifications --strategy apidoc
time timeout 1800 python main.py --mode relancer --project russellyates88_suicide-rates-overview-1985-to-2016 --notebook suicide-rate-analysis-using-decesion-tree --strategy apidoc
time timeout 1800 python main.py --mode relancer --project russellyates88_suicide-rates-overview-1985-to-2016 --notebook suicide-analysis-by-random-forest --strategy apidoc
time timeout 1800 python main.py --mode relancer --project neuromusic_avocado-prices --notebook is-your-avocado-organic-or-not --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook decision-trees-and-random-forest-tutorial --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook simple-logistic-regression-for-employee-attrition --strategy apidoc
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook customer-churn-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook telco-churn-recommendation-eda-classification --strategy apidoc
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook prices-prediction-knn-and-decision-tree --strategy apidoc
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook housepricingknn --strategy apidoc
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook king-county-s-housing-market-various-techniques --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mirichoi0218_insurance --notebook medical-insurance-cost-linear-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mirichoi0218_insurance --notebook python-exploratoryanalysis-decisiontree --strategy apidoc
time timeout 1800 python main.py --mode relancer --project annavictoria_speed-dating-experiment --notebook daraspeeding-decision-features-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project nicapotato_womens-ecommerce-clothing-reviews --notebook customer-feedback-analyzing-system --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook gender-voice-recognize-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook extracting-results-by-visualizing-and-applying-svm --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook support-vector-machine-detail-analysis-test --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook diamond-exploratory-analysis-and-visualizations --strategy apidoc
time timeout 1800 python main.py --mode relancer --project benroshan_factors-affecting-campus-placement --notebook how-about-getting-placements-a-data-exploration --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook analysis-and-prediction-of-student-performance --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook students-scores-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook predicting-housing-prices-using-linear-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook linear-regression-predicting-house-prices --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook employee-attrition-via-ensemble-tree-based-methods --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook decisiontree-and-randomforest --strategy apidoc
time timeout 1800 python main.py --mode relancer --project chirin_africa-economic-banking-and-systemic-crisis-data --notebook african-crisis-eda-and-modelling --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook lower-back-pain-predictive-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook logistic-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project hesh97_titanicdataset-traincsv --notebook titanic-logistic-regression-7655 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dipam7_student-grade-prediction --notebook student-grade-prediction-using-decisiontree --strategy apidoc
time timeout 1800 python main.py --mode relancer --project amanajmera1_framingham-heart-study-dataset --notebook heart-disease-prediction-using-logistic-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kingburrito666_cannabis-strains --notebook predict-cannabis-species-through-pipeline --strategy apidoc
time timeout 1800 python main.py --mode relancer --project merishnasuwal_breast-cancer-prediction-dataset --notebook breast-cancer-prediction-decision-tree --strategy apidoc
time timeout 1800 python main.py --mode relancer --project tovarischsukhov_southparklines --notebook predicting-south-park-dialogues --strategy apidoc
time timeout 1800 python main.py --mode relancer --project schirmerchad_bostonhoustingmlnd --notebook first-simple-linear-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project anderas_car-consume --notebook day3-work-akiramizuno --strategy apidoc
time timeout 1800 python main.py --mode relancer --project anderas_car-consume --notebook day3-work --strategy apidoc
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook income-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook fork-of-income-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project saurabh00007_diabetescsv --notebook pima-diabetes --strategy apidoc
time timeout 1800 python main.py --mode relancer --project piyushgoyal443_red-wine-dataset --notebook quality-of-red-wine-with-different-classifiers --strategy apidoc
time timeout 1800 python main.py --mode relancer --project crawford_1000-cameras-dataset --notebook fork-of-regression-challenge-day-3 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project zhangjuefei_birds-bones-and-living-habits --notebook classifiers-algorithm-implementation-bird-data --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rakeshrau_social-network-ads --notebook item-purchased-or-not --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dragonheir_logistic-regression --notebook kernel76e4019a08 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dragonheir_logistic-regression --notebook logistic-regression-by-sklearn-2 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rouseguy_bankbalanced --notebook ml-bank-marketing-solution --strategy apidoc
time timeout 1800 python main.py --mode relancer --project patelprashant_employee-attrition --notebook attrition-using-linear-discriminant-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rohankayan_years-of-experience-and-salary-dataset --notebook salary-and-experince-simple-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project karangadiya_fifa19 --notebook fifa-2019-regression-model --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook types-of-regression-and-stats-in-depth --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook step-by-step-regression-backward-elimination --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook exploratory-data-analysis-logistic-and-xgboost --strategy apidoc
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook california-housing-optimised-modelling --strategy apidoc
time timeout 1800 python main.py --mode relancer --project schirmerchad_bostonhoustingmlnd --notebook boston-pred-analysis-regression-regularization --strategy apidoc
time timeout 1800 python main.py --mode relancer --project crawford_weekly-sales-transactions --notebook sales-exploration --strategy apidoc
time timeout 1800 python main.py --mode relancer --project crawford_1000-cameras-dataset --notebook camera-notes --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project ricardomoya_football-matches-of-spanish-league --notebook el-cl-sico-2019-20-real-madrid-or-barcelona-dl --strategy apidoc
time timeout 1800 python main.py --mode relancer --project arshid_iris-flower-dataset --notebook lr-svm-on-iris --strategy apidoc # ------
time timeout 1800 python main.py --mode relancer --project lumins_settlers-of-catan-games --notebook logistic-regression-and-knn-predictors --strategy apidoc
time timeout 1800 python main.py --mode relancer --project koki25ando_hostel-world-dataset --notebook regression-mlr-lasso-ridge-and-elastic --strategy apidoc
time timeout 1800 python main.py --mode relancer --project gilsousa_habermans-survival-data-set --notebook haberman-s-survival --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook analyzing-the-heart-disease --strategy apidoc
time timeout 1800 python main.py --mode relancer --project neuromusic_avocado-prices --notebook explore-avocados-from-all-sides --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook data-analysis-student-s-behavior --strategy apidoc
time timeout 1800 python main.py --mode relancer --project budincsevity_szeged-weather --notebook simple-linear-regression-using-weatherhistory-data --strategy apidoc
time timeout 1800 python main.py --mode relancer --project schirmerchad_bostonhoustingmlnd --notebook predicting-boston-house-prices --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook student-peroformance-analysis --strategy apidoc # ------
time timeout 1800 python main.py --mode relancer --project johndasilva_diabetes --notebook diabetes-classifications --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rodolfomendes_abalone-dataset --notebook abalone-rings --strategy apidoc
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook simple-exploration-using-tensorflow-regression --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook simple-logistic-and-random-forest-examle --strategy apidoc
time timeout 1800 python main.py --mode relancer --project adammaus_predicting-churn-for-bank-customers --notebook bank-churn-analysis-with-roc-auc-score-of-0-95 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project flenderson_sales-analysis --notebook kernele7f4dbb964 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook bank-customer-churn-mlp-with-keras --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mirichoi0218_insurance --notebook patient-charges-regression-and-classification --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aungpyaeap_fish-market --notebook weight-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook churn-prediction-telecom --strategy apidoc
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook tree-based-ensemble-models --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook predicting-student-academic-performance --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rodolfomendes_abalone-dataset --notebook abalone-machine-learning-insights --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook predicting-diamond-prices-using-knn-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook diamonds-in-depth-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook predicting-diamond-prices-using-linear-svm --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook knn-regression-and-cross-validation --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook diamond-detailed-eda-feature-eng-model-acc-98 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project datasnaek_league-of-legends --notebook let-s-predict-league-of-legends-match-score --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mrisdal_married-at-first-sight --notebook married-at-first-sight-notebook --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook ibm-analytics --strategy apidoc
time timeout 1800 python main.py --mode relancer --project joniarroba_noshowappointments --notebook predict-missed-appointments-with-80-accuracy --strategy apidoc
time timeout 1800 python main.py --mode relancer --project benroshan_factors-affecting-campus-placement --notebook campusplacement --strategy apidoc
time timeout 1800 python main.py --mode relancer --project yersever_500-person-gender-height-weight-bodymassindex --notebook analysis-and-building-a-model-for-bmi-data --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mansoordaku_ckdisease --notebook eda-on-chronic-kidney-disease --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mansoordaku_ckdisease --notebook chronic-kidney-disease-eda-and-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook fighting-off-overly-optimistic-score --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook what-causes-heart-disease --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook image-processing-ct-scan --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook single-convolution-layer --strategy apidoc 
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook keras-unet --strategy apidoc
time timeout 1800 python main.py --mode relancer --project toramky_automobile-dataset --notebook auto-imports-beginner-level-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project toramky_automobile-dataset --notebook linear-model-for-price-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rtatman_did-it-rain-in-seattle-19482017 --notebook will-it-rain-in-seattle --strategy apidoc
time timeout 1800 python main.py --mode relancer --project abcsds_pokemon --notebook pokemon-classification-and-smote-for-imbalance --strategy apidoc
time timeout 1800 python main.py --mode relancer --project annavictoria_speed-dating-experiment --notebook does-everyone-like-the-same-people-eda --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook churn-fraud-kantapong-62199130227 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project filippoo_deep-learning-az-ann --notebook neural-network --strategy apidoc
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook telecom-customer-churn --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook gender-recognition-nn --strategy apidoc
time timeout 1800 python main.py --mode relancer --project roshansharma_online-shoppers-intention --notebook shopper-s-intention-classification-xgboost-lightgm --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook heart-disease-prediction-accuracy-84-5 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project lumins_settlers-of-catan-games --notebook data-exploration-simple-rf-model --strategy apidoc


# ====================================

### --- type inference ----
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook kaggle-bank-turnover-dataset-churnnochurn-dl --strategy apidoc
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook keras-ann-bank-turnover-dataset --strategy apidoc
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook artificial-neural-networks-ann-keras --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook churn-modelling-dl --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shubh0799_churn-modelling --notebook churn-modelling-ann --strategy apidoc
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook simple-neural-networks-using-keras --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook deep-learning-26102562 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook bank-customers-churn-ann --strategy apidoc
time timeout 1800 python main.py --mode relancer --project r3w0p4_bournemouth-venues --notebook bournemouth-venues-analisis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aakash50897_churn-modellingcsv --notebook bank-churning-model-using-artififcal-neural-net --strategy apidoc
time timeout 1800 python main.py --mode relancer --project abcsds_pokemon --notebook pok-mon-type-prediction-with-keras --strategy apidoc
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook copy-fix-house-price-prediction-1-2 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project merishnasuwal_breast-cancer-prediction-dataset --notebook work-in-progress-xgboost --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dronio_SolarEnergy --notebook pysolar-dataset-exploration-and-r99-88 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook different-methods-to-learn-data-classification --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mirichoi0218_insurance --notebook statistical-analysis-ml-cost-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook sex-recognition-by-voice-using-ann-eda-n-feature --strategy apidoc
time timeout 1800 python main.py --mode relancer --project apratim87_housingdata --notebook revising-linear-regression-using-housing-prices --strategy apidoc
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook logistic-regression-scratch-implementation --strategy apidoc
time timeout 1800 python main.py --mode relancer --project joniarroba_noshowappointments --notebook predicting-a-no-show --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook student-perfomance --strategy apidoc
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook house-price-prediction-part-2 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dansbecker_nba-shot-logs --notebook predict-if-a-shot-is-made --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook imbalanceddata-predictivemodelling-by-ibm-dataset --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook an-introduction-to-ann-keras-with-ibm-hr-dataset --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rtatman_did-it-rain-in-seattle-19482017 --notebook seattle-rain-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook lower-back-pain-symptoms-smote-parameter-tuning --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook a-complete-tutorial-onpredictive-modeling-acc-99 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kabure_german-credit-data-with-risk --notebook german-credit-analysis-a-risk-perspective --strategy apidoc
### --- complex fix ---
time timeout 1800 python main.py --mode relancer --project bobbyscience_league-of-legends-diamond-ranked-games-10-min --notebook analysing-legends --strategy apidoc
time timeout 1800 python main.py --mode relancer --project maajdl_yeh-concret-data --notebook tensor-flow-strength-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project hugodarwood_celebrity-deaths --notebook predictions-for-2017 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project neuromusic_avocado-prices --notebook avocado-exploratory-and-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project deadskull7_fer2013 --notebook fer-2013-notebook --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rounakbanik_pokemon --notebook pokemon-comparison-between-nn-and-rf --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook voice-gender-random-forest-xgboost-nn --strategy apidoc
### --- complex fix ---
time timeout 1800 python main.py --mode relancer --project neuromusic_avocado-prices --notebook taller-utp-2019-julio --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook customer-churn-modelling --strategy apidoc
time timeout 1800 python main.py --mode relancer --project deadskull7_fer2013 --notebook efficiennet-b3 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook artificial-nn-churn-prediction --strategy apidoc
### --- complex fix ---
time timeout 1800 python main.py --mode relancer --project nsrose7224_crowdedness-at-the-campus-gym --notebook forecasting-with-facebook-prophet --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook tensorflow-gender-classification --strategy apidoc
time timeout 1800 python main.py --mode relancer --project patelprashant_employee-attrition --notebook eda-and-modelling-employee-attrition --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook gbrt-rf-nb-tf-visualization-and-preprocess --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook l-back-pain-solutions --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dansbecker_nba-shot-logs --notebook basketball-shot-prediction-model --strategy apidoc
### --- complex fix ---
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook detailed-parameter-analysis-and-tuning-97-004 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project utathya_imdb-review-dataset --notebook kernelca3a6fa0c9 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook employee-churn-model-w-strategic-retention-plan --strategy apidoc
### --- developers' errors ---
time timeout 1800 python main.py --mode relancer --project maajdl_yeh-concret-data --notebook strength-prediction-using-linear-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project elikplim_forest-fires-data-set --notebook the-burned-area-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook polynomialregression-backwardeliminationtech --strategy apidoc
time timeout 1800 python main.py --mode relancer --project jenny18_honey-bee-annotated-images --notebook what-kind-of-bee-am-i --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook segmentation-lung-from-ct --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook simple-nn-with-keras --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook lung-segmentation-combined-approach --strategy apidoc
time timeout 1800 python main.py --mode relancer --project deadskull7_fer2013 --notebook efficientnet-b1 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook heart-disease-prediction-90-accuracy --strategy apidoc
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook churn-model-using-random-forest-vsm-and-ann --strategy apidoc
time timeout 1800 python main.py --mode relancer --project joniarroba_noshowappointments --notebook from-eda-to-modeling --strategy apidoc
time timeout 1800 python main.py --mode relancer --project ajay1735_hmeq-data --notebook ml-with-random-forest-and-naive-bayes-classifier --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sudalairajkumar_indian-startup-funding --notebook eda-and-ensemble-methods-on-startup-funding --strategy apidoc
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook exploratory-data-analysis-and-clustering --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook lower-back-pain-analyze-and-supervised-learning --strategy apidoc
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook income-prediction-using-l-r --strategy apidoc
time timeout 1800 python main.py --mode relancer --project budincsevity_szeged-weather --notebook regression-challenge-day-1 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mathijs_weather-data-in-new-york-city-2016 --notebook new-york-city-taxi-playground-with-xgboost --strategy apidoc
time timeout 1800 python main.py --mode relancer --project stevezhenghp_airbnb-price-prediction --notebook nyc-airbnb-regression-project --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kevinmh_fifa-18-more-complete-player-dataset --notebook fifa-world-cup-2018-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project rounakbanik_pokemon --notebook improving-pokemon-generation-1-predictions --strategy apidoc
time timeout 1800 python main.py --mode relancer --project tadhgfitzgerald_fifa-international-soccer-mens-ranking-1993now --notebook fifa-world-cup-2018-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook roni-california-housing-prices --strategy apidoc
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook geospatial-feature-engineering-and-visualization --strategy apidoc
time timeout 1800 python main.py --mode relancer --project neuromusic_avocado-prices --notebook autoregressive-model --strategy apidoc
time timeout 1800 python main.py --mode relancer --project everling_cocaine-listings --notebook what-drives-the-cocaine-cost --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dansbecker_melbourne-housing-snapshot --notebook iowa-housing-price-predictor-using-xgboost --strategy apidoc
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook telco-customer-churn-eda-and-classification --strategy apidoc
time timeout 1800 python main.py --mode relancer --project joniarroba_noshowappointments --notebook baseline-eda-pipe-modelling-w-hparam-easy-code --strategy apidoc
time timeout 1800 python main.py --mode relancer --project utathya_imdb-review-dataset --notebook sentiment-analysis-of-imdb-reviews --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook employee-churn-model --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook baseline-eda-and-attrition-prediction-pipeline --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook analysing-classifiers --strategy apidoc
time timeout 1800 python main.py --mode relancer --project filippoo_deep-learning-az-ann --notebook customer-churn-modelling-using-ann-86-accuracy --strategy apidoc
time timeout 1800 python main.py --mode relancer --project zhijinzhai_loandata --notebook the-best-classifier-loan-pridiction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutibhargava94_india-air-quality-data --notebook air-quality-index-analysis-ml-visualisation --strategy apidoc
time timeout 1800 python main.py --mode relancer --project budincsevity_szeged-weather --notebook weather-prediction-regression-neural-model --strategy apidoc
time timeout 1800 python main.py --mode relancer --project budincsevity_szeged-weather --notebook weatherpredict --strategy apidoc
time timeout 1800 python main.py --mode relancer --project muthuj7_weather-dataset --notebook weatherpredict --strategy apidoc
time timeout 1800 python main.py --mode relancer --project jojoker_singapore-airbnb --notebook feature-engineering-for-regressions-models --strategy apidoc
time timeout 1800 python main.py --mode relancer --project xwolf12_datasetandroidpermissions --notebook android-malware-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook hr-analytics-random-forests-and-gradient-boosting --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mrferozi_loan-data-for-dummy-bank --notebook default-analysis --strategy apidoc
time timeout 1800 python main.py --mode relancer --project giripujar_hr-analytics --notebook hr-analytics-practice --strategy apidoc
time timeout 1800 python main.py --mode relancer --project mustafaali96_weight-height --notebook height-weight-prediction-using-regression --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kabure_german-credit-data-with-risk --notebook credit-risk-classification --strategy apidoc
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook simple-implementation-of-neural-net --strategy apidoc
time timeout 1800 python main.py --mode relancer --project adammaus_predicting-churn-for-bank-customers --notebook kernel3bed9143b3 --strategy apidoc
time timeout 1800 python main.py --mode relancer --project dipam7_student-grade-prediction --notebook tensor-flow-grade-prediction --strategy apidoc
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook spinal-abnormalities-an-ul-approach --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook artificial-neural-network-to-classify-voice --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook ann-keras-churn-modelling --strategy apidoc
time timeout 1800 python main.py --mode relancer --project adammaus_predicting-churn-for-bank-customers --notebook kernel7e0fb4005c --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook gender-voice-recog-tfkeras --strategy apidoc
time timeout 1800 python main.py --mode relancer --project johnsmith88_heart-disease-dataset --notebook recognizing-heart-disease-with-neural-networks --strategy apidoc
### --- time out cases ---
time timeout 1800 python main.py --mode relancer --project loveall_appliances-energy-prediction --notebook appliances-energy-prediction-lstm-arima-fbprophet --strategy apidoc
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook gender-classification-based-on-voice-data --strategy apidoc
time timeout 1800 python main.py --mode relancer --project gregorut_videogamesales --notebook predicting-game-sales-in-na --strategy apidoc
### --- time out cases ---
time timeout 1800 python main.py --mode relancer --project hmavrodiev_london-bike-sharing-dataset --notebook advanced-visualizations-and-predictions-with-lstm --strategy apidoc
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook bank-customer-churn-modeling --strategy apidoc
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook bank-churn-prediction-grid-search-vs-threshold-m --strategy apidoc
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook cnn-with-keras --strategy apidoc
time timeout 1800 python main.py --mode relancer --project filippoo_deep-learning-az-ann --notebook golden-buzzer --strategy apidoc
time timeout 1800 python main.py --mode relancer --project janiobachmann_bank-marketing-dataset --notebook bank-marketing-using-logistic-and-neural-network --strategy apidoc

date

cd -
