#!/bin/bash

cd ../../

date

time timeout 1800 python main.py --mode relancer --project gregorut_videogamesales --notebook did-you-said-basics-eda-ml-for-very-beginners --strategy naive # ------
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook ibm-hr-prediction-and-data-visualization --strategy naive
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook insightful-eda-churn-customers-models-pipeline --strategy naive
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook first-kaggle-stat-analysis-eda-adjusted-r-2-87 --strategy naive
time timeout 1800 python main.py --mode relancer --project vjchoudhary7_customer-segmentation-tutorial-in-python --notebook unsupervised-learning-applications --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook student-s-academic-performance-with-ml-eda --strategy naive
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook heart-disease-prediction-with-ml-models --strategy naive 
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook machine-learning-classification --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook an-eda-on-sap --strategy naive
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook end-to-end-ml-project --strategy naive 
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook california-housing-tutorial --strategy naive 
time timeout 1800 python main.py --mode relancer --project alopez247_pokemon --notebook sklearn-tutorial --strategy naive
time timeout 1800 python main.py --mode relancer --project imnikhilanand_heart-attack-prediction --notebook heart-attack-detection-proj1 --strategy naive
time timeout 1800 python main.py --mode relancer --project janiobachmann_bank-marketing-dataset --notebook bank-marketing-campaign-opening-a-term-deposit --strategy naive
time timeout 1800 python main.py --mode relancer --project janiobachmann_bank-marketing-dataset --notebook marketing-campaign --strategy naive
time timeout 1800 python main.py --mode relancer --project aungpyaeap_fish-market --notebook kernel49cd9d947d --strategy naive
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook telecom-churn --strategy naive
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook bank-churn-modelling --strategy naive
time timeout 1800 python main.py --mode relancer --project fayomi_advertising --notebook ad-click-prediction-using-logistic-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project mansoordaku_ckdisease --notebook data-cleaning-classification-algorithms-comparison --strategy naive
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook decision-tree-f1-98-acc-99-auc-99 --strategy naive 
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook income-prediction-using-multi-model-and-eda --strategy naive
time timeout 1800 python main.py --mode relancer --project loveall_appliances-energy-prediction --notebook appliance-energy-prediction --strategy naive 
time timeout 1800 python main.py --mode relancer --project ruslankl_mice-protein-expression --notebook behavior-based-on-protein-expression-using-svm --strategy naive
time timeout 1800 python main.py --mode relancer --project jruvika_fake-news-detection --notebook fake-news-classifier --strategy naive
time timeout 1800 python main.py --mode relancer --project madislemsalu_facebook-ad-campaign --notebook who-is-likely-to-have-approved-transactions --strategy naive
time timeout 1800 python main.py --mode relancer --project kingburrito666_shakespeare-plays --notebook text-generation-using-shakespeare-plays --strategy naive 
time timeout 1800 python main.py --mode relancer --project kandij_diabetes-dataset --notebook diabetics-prediction-using-logistic-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project gunner38_horseracing --notebook logistic-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project rtatman_us-candy-production-by-month --notebook sweet-time-series --strategy naive
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook application-of-supervised-ml-classifications --strategy naive
time timeout 1800 python main.py --mode relancer --project russellyates88_suicide-rates-overview-1985-to-2016 --notebook suicide-rate-analysis-using-decesion-tree --strategy naive
time timeout 1800 python main.py --mode relancer --project russellyates88_suicide-rates-overview-1985-to-2016 --notebook suicide-analysis-by-random-forest --strategy naive
time timeout 1800 python main.py --mode relancer --project neuromusic_avocado-prices --notebook is-your-avocado-organic-or-not --strategy naive 
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook decision-trees-and-random-forest-tutorial --strategy naive
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook simple-logistic-regression-for-employee-attrition --strategy naive
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook customer-churn-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project blastchar_telco-customer-churn --notebook telco-churn-recommendation-eda-classification --strategy naive
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook prices-prediction-knn-and-decision-tree --strategy naive
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook housepricingknn --strategy naive
time timeout 1800 python main.py --mode relancer --project harlfoxem_housesalesprediction --notebook king-county-s-housing-market-various-techniques --strategy naive
time timeout 1800 python main.py --mode relancer --project mirichoi0218_insurance --notebook medical-insurance-cost-linear-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project mirichoi0218_insurance --notebook python-exploratoryanalysis-decisiontree --strategy naive
time timeout 1800 python main.py --mode relancer --project annavictoria_speed-dating-experiment --notebook daraspeeding-decision-features-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project nicapotato_womens-ecommerce-clothing-reviews --notebook customer-feedback-analyzing-system --strategy naive
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook gender-voice-recognize-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook extracting-results-by-visualizing-and-applying-svm --strategy naive
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook support-vector-machine-detail-analysis-test --strategy naive 
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook diamond-exploratory-analysis-and-visualizations --strategy naive
time timeout 1800 python main.py --mode relancer --project benroshan_factors-affecting-campus-placement --notebook how-about-getting-placements-a-data-exploration --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook analysis-and-prediction-of-student-performance --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook students-scores-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook predicting-housing-prices-using-linear-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook linear-regression-predicting-house-prices --strategy naive
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook employee-attrition-via-ensemble-tree-based-methods --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook decisiontree-and-randomforest --strategy naive
time timeout 1800 python main.py --mode relancer --project chirin_africa-economic-banking-and-systemic-crisis-data --notebook african-crisis-eda-and-modelling --strategy naive
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook lower-back-pain-predictive-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook logistic-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project hesh97_titanicdataset-traincsv --notebook titanic-logistic-regression-7655 --strategy naive
time timeout 1800 python main.py --mode relancer --project dipam7_student-grade-prediction --notebook student-grade-prediction-using-decisiontree --strategy naive
time timeout 1800 python main.py --mode relancer --project amanajmera1_framingham-heart-study-dataset --notebook heart-disease-prediction-using-logistic-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project kingburrito666_cannabis-strains --notebook predict-cannabis-species-through-pipeline --strategy naive
time timeout 1800 python main.py --mode relancer --project merishnasuwal_breast-cancer-prediction-dataset --notebook breast-cancer-prediction-decision-tree --strategy naive
time timeout 1800 python main.py --mode relancer --project tovarischsukhov_southparklines --notebook predicting-south-park-dialogues --strategy naive
time timeout 1800 python main.py --mode relancer --project schirmerchad_bostonhoustingmlnd --notebook first-simple-linear-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project anderas_car-consume --notebook day3-work-akiramizuno --strategy naive
time timeout 1800 python main.py --mode relancer --project anderas_car-consume --notebook day3-work --strategy naive
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook income-prediction --strategy naive
time timeout 1800 python main.py --mode relancer --project wenruliu_adult-income-dataset --notebook fork-of-income-prediction --strategy naive
time timeout 1800 python main.py --mode relancer --project saurabh00007_diabetescsv --notebook pima-diabetes --strategy naive
time timeout 1800 python main.py --mode relancer --project piyushgoyal443_red-wine-dataset --notebook quality-of-red-wine-with-different-classifiers --strategy naive
time timeout 1800 python main.py --mode relancer --project crawford_1000-cameras-dataset --notebook fork-of-regression-challenge-day-3 --strategy naive
time timeout 1800 python main.py --mode relancer --project zhangjuefei_birds-bones-and-living-habits --notebook classifiers-algorithm-implementation-bird-data --strategy naive
time timeout 1800 python main.py --mode relancer --project rakeshrau_social-network-ads --notebook item-purchased-or-not --strategy naive
time timeout 1800 python main.py --mode relancer --project dragonheir_logistic-regression --notebook kernel76e4019a08 --strategy naive
time timeout 1800 python main.py --mode relancer --project dragonheir_logistic-regression --notebook logistic-regression-by-sklearn-2 --strategy naive
time timeout 1800 python main.py --mode relancer --project rouseguy_bankbalanced --notebook ml-bank-marketing-solution --strategy naive
time timeout 1800 python main.py --mode relancer --project patelprashant_employee-attrition --notebook attrition-using-linear-discriminant-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project rohankayan_years-of-experience-and-salary-dataset --notebook salary-and-experince-simple-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project karangadiya_fifa19 --notebook fifa-2019-regression-model --strategy naive
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook types-of-regression-and-stats-in-depth --strategy naive
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook step-by-step-regression-backward-elimination --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook exploratory-data-analysis-logistic-and-xgboost --strategy naive
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook california-housing-optimised-modelling --strategy naive
time timeout 1800 python main.py --mode relancer --project schirmerchad_bostonhoustingmlnd --notebook boston-pred-analysis-regression-regularization --strategy naive
time timeout 1800 python main.py --mode relancer --project crawford_weekly-sales-transactions --notebook sales-exploration --strategy naive
time timeout 1800 python main.py --mode relancer --project crawford_1000-cameras-dataset --notebook camera-notes --strategy naive 
time timeout 1800 python main.py --mode relancer --project ricardomoya_football-matches-of-spanish-league --notebook el-cl-sico-2019-20-real-madrid-or-barcelona-dl --strategy naive
time timeout 1800 python main.py --mode relancer --project arshid_iris-flower-dataset --notebook lr-svm-on-iris --strategy naive # ------
time timeout 1800 python main.py --mode relancer --project lumins_settlers-of-catan-games --notebook logistic-regression-and-knn-predictors --strategy naive
time timeout 1800 python main.py --mode relancer --project koki25ando_hostel-world-dataset --notebook regression-mlr-lasso-ridge-and-elastic --strategy naive
time timeout 1800 python main.py --mode relancer --project gilsousa_habermans-survival-data-set --notebook haberman-s-survival --strategy naive
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook analyzing-the-heart-disease --strategy naive
time timeout 1800 python main.py --mode relancer --project neuromusic_avocado-prices --notebook explore-avocados-from-all-sides --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook data-analysis-student-s-behavior --strategy naive
time timeout 1800 python main.py --mode relancer --project budincsevity_szeged-weather --notebook simple-linear-regression-using-weatherhistory-data --strategy naive
time timeout 1800 python main.py --mode relancer --project schirmerchad_bostonhoustingmlnd --notebook predicting-boston-house-prices --strategy naive 
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook student-peroformance-analysis --strategy naive # ------
time timeout 1800 python main.py --mode relancer --project johndasilva_diabetes --notebook diabetes-classifications --strategy naive
time timeout 1800 python main.py --mode relancer --project rodolfomendes_abalone-dataset --notebook abalone-rings --strategy naive
time timeout 1800 python main.py --mode relancer --project camnugent_california-housing-prices --notebook simple-exploration-using-tensorflow-regression --strategy naive 
time timeout 1800 python main.py --mode relancer --project sammy123_lower-back-pain-symptoms-dataset --notebook simple-logistic-and-random-forest-examle --strategy naive
time timeout 1800 python main.py --mode relancer --project adammaus_predicting-churn-for-bank-customers --notebook bank-churn-analysis-with-roc-auc-score-of-0-95 --strategy naive
time timeout 1800 python main.py --mode relancer --project flenderson_sales-analysis --notebook kernele7f4dbb964 --strategy naive
time timeout 1800 python main.py --mode relancer --project barelydedicated_bank-customer-churn-modeling --notebook bank-customer-churn-mlp-with-keras --strategy naive
time timeout 1800 python main.py --mode relancer --project mirichoi0218_insurance --notebook patient-charges-regression-and-classification --strategy naive
time timeout 1800 python main.py --mode relancer --project aungpyaeap_fish-market --notebook weight-prediction --strategy naive
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook churn-prediction-telecom --strategy naive
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook tree-based-ensemble-models --strategy naive
time timeout 1800 python main.py --mode relancer --project aljarah_xAPI-Edu-Data --notebook predicting-student-academic-performance --strategy naive
time timeout 1800 python main.py --mode relancer --project rodolfomendes_abalone-dataset --notebook abalone-machine-learning-insights --strategy naive
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook predicting-diamond-prices-using-knn-regression --strategy naive
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook diamonds-in-depth-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook predicting-diamond-prices-using-linear-svm --strategy naive
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook knn-regression-and-cross-validation --strategy naive
time timeout 1800 python main.py --mode relancer --project shivam2503_diamonds --notebook diamond-detailed-eda-feature-eng-model-acc-98 --strategy naive
time timeout 1800 python main.py --mode relancer --project datasnaek_league-of-legends --notebook let-s-predict-league-of-legends-match-score --strategy naive
time timeout 1800 python main.py --mode relancer --project mrisdal_married-at-first-sight --notebook married-at-first-sight-notebook --strategy naive
time timeout 1800 python main.py --mode relancer --project pavansubhasht_ibm-hr-analytics-attrition-dataset --notebook ibm-analytics --strategy naive
time timeout 1800 python main.py --mode relancer --project joniarroba_noshowappointments --notebook predict-missed-appointments-with-80-accuracy --strategy naive
time timeout 1800 python main.py --mode relancer --project benroshan_factors-affecting-campus-placement --notebook campusplacement --strategy naive
time timeout 1800 python main.py --mode relancer --project yersever_500-person-gender-height-weight-bodymassindex --notebook analysis-and-building-a-model-for-bmi-data --strategy naive
time timeout 1800 python main.py --mode relancer --project mansoordaku_ckdisease --notebook eda-on-chronic-kidney-disease --strategy naive
time timeout 1800 python main.py --mode relancer --project mansoordaku_ckdisease --notebook chronic-kidney-disease-eda-and-prediction --strategy naive
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook fighting-off-overly-optimistic-score --strategy naive
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook what-causes-heart-disease --strategy naive
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook image-processing-ct-scan --strategy naive
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook single-convolution-layer --strategy naive 
time timeout 1800 python main.py --mode relancer --project kmader_finding-lungs-in-ct-data --notebook keras-unet --strategy naive
time timeout 1800 python main.py --mode relancer --project toramky_automobile-dataset --notebook auto-imports-beginner-level-analysis --strategy naive
time timeout 1800 python main.py --mode relancer --project toramky_automobile-dataset --notebook linear-model-for-price-prediction --strategy naive
time timeout 1800 python main.py --mode relancer --project rtatman_did-it-rain-in-seattle-19482017 --notebook will-it-rain-in-seattle --strategy naive
time timeout 1800 python main.py --mode relancer --project abcsds_pokemon --notebook pokemon-classification-and-smote-for-imbalance --strategy naive
time timeout 1800 python main.py --mode relancer --project annavictoria_speed-dating-experiment --notebook does-everyone-like-the-same-people-eda --strategy naive
time timeout 1800 python main.py --mode relancer --project shrutimechlearn_churn-modelling --notebook churn-fraud-kantapong-62199130227 --strategy naive
time timeout 1800 python main.py --mode relancer --project filippoo_deep-learning-az-ann --notebook neural-network --strategy naive
time timeout 1800 python main.py --mode relancer --project becksddf_churn-in-telecoms-dataset --notebook telecom-customer-churn --strategy naive
time timeout 1800 python main.py --mode relancer --project primaryobjects_voicegender --notebook gender-recognition-nn --strategy naive
time timeout 1800 python main.py --mode relancer --project roshansharma_online-shoppers-intention --notebook shopper-s-intention-classification-xgboost-lightgm --strategy naive
time timeout 1800 python main.py --mode relancer --project ronitf_heart-disease-uci --notebook heart-disease-prediction-accuracy-84-5 --strategy naive
time timeout 1800 python main.py --mode relancer --project lumins_settlers-of-catan-games --notebook data-exploration-simple-rf-model --strategy naive

date

cd -
